//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capa_Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class Licencias
    {
        public int ID_LIC { get; set; }
        public Nullable<int> ID_EMP { get; set; }
        public string Desde { get; set; }
        public string Hasta { get; set; }
        public string Motivo { get; set; }
        public string Comentario { get; set; }
    }
}
